#!/bin/bash

ec2_servers="ec2-54-159-99-25.compute-1.amazonaws.com
ec2-50-18-189-64.us-west-1.compute.amazonaws.com
ec2-18-229-54-5.sa-east-1.compute.amazonaws.com
ec2-13-244-183-11.af-south-1.compute.amazonaws.com
ec2-13-36-115-83.eu-west-3.compute.amazonaws.com
ec2-13-51-89-160.eu-north-1.compute.amazonaws.com
ec2-65-1-183-44.ap-south-1.compute.amazonaws.com
ec2-13-208-85-51.ap-northeast-3.compute.amazonaws.com
ec2-54-79-190-216.ap-southeast-2.compute.amazonaws.com"

username=$8
keyfile=${10}
dns_server="cs5700cdnproject.ccs.neu.edu"

scp -i "$keyfile" dnsserver "$username"@$dns_server:~

# shellcheck disable=SC2086
ssh -i "$keyfile" $username@$dns_server "chmod +x dnsserver"

# shellcheck disable=SC2154
for server in $ec2_servers
do
  # shellcheck disable=SC2086
  scp -i "$keyfile" httpserver "$username"@$server:~
  ssh -i "$keyfile" "$username"@"$server" "chmod +x httpserver"
done

